CREATE TABLE consumer(
                         consumer_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         username varchar(60)
);

CREATE TABLE folder(
                       folder_id int primary key GENERATED by default as identity,
                       consumer_id int not null references consumer(consumer_id),
                       root_folder_id int not null references folder(folder_id),
                       folderName varchar
);

CREATE TABLE setting(
                        consumer_id int PRIMARY KEY REFERENCES consumer(consumer_id),
                        name_parameter varchar NOT NULL,
                        parameter bool NOT NULL
);
-- insert into folder( consumer_id, root_folder_id) values (1,CURRVAL('folder_folder_id_seq'));

CREATE TABLE noteJson(
                     note_id int primary key GENERATED by default as identity,
                     consumer_id int not null references consumer(consumer_id),
                     root_folder_id int not null references folder(folder_id),
                     data varchar not null
);

-- CREATE TABLE main_folder(
--     consumer_id int primary key references consumer(consumer_id),
--     folder_id int unique not null references folder(folder_id)
-- );
