create table consumer
(
    consumer_id integer generated by default as identity primary key,
    username    varchar(60)
);
create table folder
(
    folder_id        integer generated by default as identity primary key,
    consumer_id      integer not null references consumer  on delete cascade ,
    parent_folder_id integer not null references folder on delete cascade ,
    folder_name      varchar
);

create table setting
(
    consumer_id    integer not null primary key references consumer  on delete cascade ,
    name_parameter varchar not null,
    parameter      boolean not null
);

create table note
(
    note_id          integer generated by default as identity primary key,
    consumer_id      integer not null references consumer  on delete cascade ,
    parent_folder_id integer not null references folder  on delete cascade ,
    note_data        varchar not null,
    note_name        varchar(60)
);
